pipeline 

{
agent 
    {
       label 'master'
    }


environment 
    {
      CSV_PATH = "${WORKSPACE}/uim_file_transfer.csv"
	  CSV_FILE = "${WORKSPACE}/uim_file_transfer.csv"
    }
 stages 
   {
     stage('Verifying: CSV file')
       {
         steps 
             {
              sh ''' 
                 sh ${WORKSPACE}/osm/verify.sh                  	 
        	 '''
             } 
       
       }
    
    
    stage('Backup in Target Server')
       {
         steps
             {
              
                 sh ''' echo "Backup the files to target environment" '''    							 
                   
           
        		
             }

       }
     
    stage('copying files to Target Server')
       {
         steps
             {
             
              
                 sh ''' echo "Copy the files to target environment" '''         
           
             }

       }

 }
post 
   {
      failure
          {

             sh ''' echo "send the data to elastcisearch"  ''' 
             
          }
      
       success
         {
 
           sh ''' echo "send the data to elastcisearch"  '''
             
         } 



  }
}

